// GENERATED CODE, DO NOT EDIT THIS FILE
package postgre

import (
	"github.com/Furiady/skripsi/db-migration/dbMigration/helper/migration"
	"gorm.io/gorm"
)

func InitializeMigrations(conn *gorm.DB) []migration.Migration {
	var migrations = make([]migration.Migration, 0)
	return migrations
} 