openapi: 3.0.0
x-stoplight:
  id: oqys2nsi6r698
info:
  title: Common
  version: '1.0'
  contact: {}
  description: Holds the common model that will be used by other APIs
servers:
  - url: 'http://localhost:9000'
paths: {}
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: zsvgmpt0zpr40
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: 5xl948ll9elmk
        email:
          type: string
          x-stoplight:
            id: nq2u3kyro9tup
          format: email
        username:
          type: string
          x-stoplight:
            id: v8uhz39lsjvqw
        pin:
          type: string
          x-stoplight:
            id: yzyp5c8aclqlk
        coin:
          type: integer
          x-stoplight:
            id: gphsdjadmctd0
        gamification:
          type: string
          x-stoplight:
            id: gb427b968g2c9
      required:
        - id
        - email
        - username
        - pin
        - coin
        - gamification
    Record:
      title: Record
      x-stoplight:
        id: k9kpycq929fjr
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          x-stoplight:
            id: uj8s2gpae9xio
        description:
          type: string
          x-stoplight:
            id: aj539zvbstjrl
        type:
          type: string
          x-stoplight:
            id: 080rvcqxnymob
        category:
          type: string
          x-stoplight:
            id: 3317vgl9r15xx
        value:
          type: integer
          x-stoplight:
            id: jfk1245sw3oal
          format: int64
        url:
          type: string
          x-stoplight:
            id: s5ne6xnvmxjce
        createdAt:
          type: string
          x-stoplight:
            id: m0vxbibnrauzk
        deductFrom:
          type: string
          x-stoplight:
            id: rl2cyq59fxe1b
      required:
        - id
        - title
        - description
        - type
        - category
        - value
        - createdAt
    Quest:
      title: Quest
      x-stoplight:
        id: 4xarxbo8t0e2n
      type: object
      properties:
        id:
          type: string
        title:
          type: string
          x-stoplight:
            id: v6wyt0lk31ln1
        description:
          type: string
          x-stoplight:
            id: b38fiuwn4zbgm
        reward:
          type: integer
          x-stoplight:
            id: 8ildu6ofrbscq
        cooldown:
          type: integer
          x-stoplight:
            id: ap98cidk4fd6c
        status:
          type: boolean
          x-stoplight:
            id: jzeccs2br32ry
        updatedAt:
          type: string
          x-stoplight:
            id: 8hlfu9jsb483y
      required:
        - id
        - title
        - description
        - reward
        - cooldown
        - status
        - updatedAt
    Pet:
      title: Pet
      x-stoplight:
        id: 8tfjwblnzgxej
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          x-stoplight:
            id: 2eggaxf4t7hg5
        price:
          type: integer
          x-stoplight:
            id: 4ku4ojalop6k4
        status:
          type: boolean
          x-stoplight:
            id: z8r3qtfi583e2
        path:
          type: string
          x-stoplight:
            id: 2q1helra90w1c
      required:
        - id
        - name
        - price
        - status
        - path
    Accessory:
      title: Accessory
      x-stoplight:
        id: 7saogffi52c9v
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          x-stoplight:
            id: r9wu5d6yqykoa
        price:
          type: integer
          x-stoplight:
            id: 78xmhh0glapz6
        status:
          type: boolean
          x-stoplight:
            id: h042gkhp823o1
        path:
          type: string
          x-stoplight:
            id: 5e0ru06jdby3f
      required:
        - id
        - name
        - price
        - status
        - path
    Theme:
      title: Theme
      x-stoplight:
        id: cotvqo8c1g9m5
      type: object
      properties:
        id:
          type: string
          format: int64
        name:
          type: string
          x-stoplight:
            id: wqdi1xe4u9xml
        price:
          type: integer
          x-stoplight:
            id: z7s3ca7c4a5p3
        status:
          type: boolean
          x-stoplight:
            id: cbwjmep6kuxy5
        path:
          type: string
          x-stoplight:
            id: i5fy8x41h1t17
      required:
        - id
        - name
        - price
        - status
        - path
    BaseResponse:
      title: BaseResponse
      x-stoplight:
        id: 2te4mztk83lq1
      type: object
      properties:
        message:
          type: string
          x-stoplight:
            id: 4pg8sz4lm3kpv
        timestamp:
          type: string
          x-stoplight:
            id: m3p6qut14mql4
      required:
        - message
        - timestamp
