openapi: 3.0.0
x-stoplight:
  id: j1s9tpnt7n0lf
info:
  contact: {}
  title: theme
  version: '1.0'
  description: APIs regarding theme
paths:
  /themes:
    get:
      summary: Your GET endpoint
      tags:
        - Theme
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./common.yaml#/components/schemas/Theme
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: ./common.yaml#/components/schemas/BaseResponse
      operationId: get-all
      requestBody:
        content: {}
      description: Get list of theme
      parameters: []
  /theme:
    post:
      summary: ''
      operationId: buy-theme
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./common.yaml#/components/schemas/BaseResponse
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: ./common.yaml#/components/schemas/BaseResponse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                themeId:
                  type: string
                  x-stoplight:
                    id: vduwfikk3wx5g
              required:
                - themeId
      description: Buy theme
      tags:
        - Theme
tags:
  - name: Theme
